# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install python3-pip zip -y
      - pip3 install -U pip
      - pip3 install awscli

  build:
    commands:
      - env
      - echo Packaging Cloudformation and uploading to S3...
      - ./package_cloudformation.sh
